from datetime import datetime

class Insight:
    """ Individual prediction/insight generated by an Alpha in the QuantConnect Alpha Streams market """

    def __init__(self, json):
    
        self.Confidence =  json.get('confidence', None)
        
        self.Created = datetime.utcfromtimestamp( json['generated-time'] )
        
        self.Direction = json.get('direction', None)
        
        self.EstimatedValue = json.get('estimated-value', None)
        
        self.GroupId = json.get('group-id', None)
        
        self.Id = json['id']
        
        self.Magnitude = json.get('magnitude', None)
        
        self.Period = json.get('period', None)
        
        self.Reference = json.get('reference', None)
        
        self.Source = json.get('source', None) # In sample
        
        self.SourceModel = json.get('source-model', None)
        
        self.SymbolId = json.get('symbol', None)
        
        self.Ticker  = json.get('ticker', None)
        
        self.Type = json.get('type', None)
        
        