from datetime import datetime

class Insight:
    """ Individual prediction/insight generated by an Alpha in the QuantConnect Alpha Streams market """

    def __init__(self, json):
    
        self.Confidence = json['confidence']
        
        self.Created = datetime.utcfromtimestamp( json['generated-time'] )
        
        self.Direction = json['direction']
        
        self.EstimatedValue = json['estimated-value']
        
        self.Id = json['id']
        
        self.Magnitude = json['magnitude']
        
        self.Period = json['period']
        
        self.Reference = json['reference']
        
        self.Source = json['source']
        
        self.SymbolId = json['symbol']
        
        self.Ticker  = json['ticker']
        
        self.Type = json['type']
        
        